CREATE TABLE IF NOT EXISTS `Companies`
(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `symbol` VARCHAR(10) NOT NULL UNIQUE,
    `name` VARCHAR(120) NOT NULL,
    `type` VARCHAR(40) DEFAULT '',
    `region` VARCHAR(80) DEFAULT '',
    `currency` VARCHAR(10) DEFAULT '',
    `is_api` TINYINT(1) DEFAULT 1,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
